version: '3.8'

networks:
  backend_network:
    external: false

services:
  products:
    build: .
    container_name: products_service
    env_file:
      - .env.test
    networks:
      - backend_network
    depends_on:
      - products_db
    command: pytest

  products_db:
    image: postgres:15
    container_name: products_test_db
    restart: "no"
    environment:
      POSTGRES_DB: products_test_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    networks:
      - backend_network