version: '3.8'


networks:
  backend_network:
    external: true

services:
  products:
    build: .
    container_name: products_service
    env_file:
      - .env.prod
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    networks:
      - backend_network
    