FROM python:3.10-slim

WORKDIR /product-service

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_APP=app.run

# CMD ["flask", "run", "--host=0.0.0.0", "--port=5001"]
CMD ["python", "-m", "app.run"]