version: '3.8'

networks:
  backend_network:
    external: false

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Connection
      - "15672:15672" # Management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend_network

  products:
    build: .
    container_name: products_service
    env_file:
      - .env.test
    networks:
      - backend_network
    depends_on:
      - products_db
      - rabbitmq
    command: pytest -s -v

  products_db:
    image: postgres:15
    container_name: products_test_db
    restart: "no"
    environment:
      POSTGRES_DB: products_test_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    networks:
      - backend_network

    