name: CI - Products-Dev

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: |
          docker compose -f ${{ github.workspace }}/docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from products
          docker compose -f ${{ github.workspace }}/docker-compose.test.yml down -v
        env:
          DATABASE_URL: ${{ secrets.PRODUCTS_SERVICE_TEST_DB_URL }}
